### PR TITLE
Add route context parameters and pathname to <Route /> children

### PR DESCRIPTION
**Pull request by Warry**
### Reference Issues/PRs

Following up https://github.com/nanojsx/nano/discussions/111

### What does this implement/fix?

Add context properties `pathname` and `params` when using `<Route/>` component, and the type `RouteProps`.

usage:
```tsx
<Router.Switch>
  <Router.Route path="/routing/:id">
    <MyComponent />
  </Router.Route>
</Router.Switch>

function MyComponent({ route }) {
    return <div>id: {route.params.id}</div>
}
```

Actually wondering if the type RouteProps is worth it.

### CODE REVIEW

**Comment by yandeu** [comment]
Thanks! Looks good.

Just need to add some tests. Should I or do you want to do it?

**Comment by Warry** [comment]
I think I can do it, either tonight or tomorrow afternoon.

What about removing `RouteProps`, I was distracted when I added it and I'm not sure it makes sense.

**Comment by Warry** [comment]
I removed the RouterProps type, I still kinda suck at typescript and couldn't make it work the way I wanted to. Reading the docs just now, it seems that I should use interface (partial typing).

It looks like I'm about to use this lib quite a lot in the upcoming months, I'll have more chances to tinker that.

BTW. Are the browser tests ran at all ?

**Comment by yandeu** [comment]
I have fixed the browser test here:
https://github.com/nanojsx/nano/commit/033c5036698eb1b48db29ee5cbca98cec19f769f

---

General question: Do you know how I can merge my changes into your PR?

**Comment by yandeu** [comment]
Cool. It worked :)

Thanks for your help and your node.js, SSR and browser tests.

**Pull request merged**
